import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

type ActivityEntry = {
  started_at: string;
  title: string;
  category: string;
  duration_secs: number;
  description: string | null;
  property: { name: string; address: string | null } | null;
};

type PropertyBreakdown = {
  name: string;
  hours: number;
  mine: number;
  spouse: number;
};

type CategoryBreakdown = {
  name: string;
  hours: number;
  mine: number;
  spouse: number;
  pct: number;
};

type PdfOptions = {
  userName: string;
  spouseName: string | null;
  showCombined: boolean;
  taxYear: number;
  goalHours: number;
  targetTest: string;
  totalHours: number;
  spouseHours: number;
  propertyBreakdown: PropertyBreakdown[];
  categoryBreakdown: CategoryBreakdown[];
  activity: ActivityEntry[];
  spouseActivity: ActivityEntry[];
  propertyFilter: string;
};

const PLUM = [58, 27, 73] as const;
const TANGERINE = [227, 108, 46] as const;
const CHAR = [45, 42, 40] as const;
const SLATE = [120, 113, 108] as const;
const CREAM = [249, 246, 240] as const;
const BONE = [232, 228, 222] as const;

export function generateTaxPdf(opts: PdfOptions) {
  const doc = new jsPDF({ orientation: "portrait", unit: "pt", format: "letter" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 50;
  const contentW = pageW - margin * 2;
  let y = margin;

  function addPageFooter() {
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(...SLATE);
      doc.text(
        `Generated by Host Hours · ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`,
        margin,
        pageH - 30,
      );
      doc.text(`Page ${i} of ${pageCount}`, pageW - margin, pageH - 30, { align: "right" });
    }
  }

  function checkPage(needed: number) {
    if (y + needed > pageH - 60) {
      doc.addPage();
      y = margin;
    }
  }

  function drawHr() {
    doc.setDrawColor(...BONE);
    doc.setLineWidth(0.5);
    doc.line(margin, y, pageW - margin, y);
    y += 12;
  }

  // ── Header ──────────────────────────────────────────────
  doc.setFillColor(...PLUM);
  doc.rect(0, 0, pageW, 100, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  doc.text("Host Hours", margin, 42);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(255, 255, 255, 180);
  doc.text("Short-Term Rental Activity Report", margin, 62);

  doc.setFontSize(13);
  doc.setTextColor(255, 255, 255);
  doc.text(`Tax Year ${opts.taxYear}`, pageW - margin, 42, { align: "right" });

  doc.setFontSize(10);
  doc.setTextColor(255, 255, 255, 180);
  const preparedFor = opts.showCombined && opts.spouseName
    ? `${opts.userName} & ${opts.spouseName}`
    : opts.userName;
  doc.text(`Prepared for ${preparedFor}`, pageW - margin, 62, { align: "right" });

  if (opts.propertyFilter !== "All properties") {
    doc.setFontSize(9);
    doc.text(`Property: ${opts.propertyFilter}`, pageW - margin, 78, { align: "right" });
  }

  y = 125;

  // ── Summary Section ─────────────────────────────────────
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...PLUM);
  doc.text("Summary", margin, y);
  y += 20;

  const irsHours = opts.showCombined ? opts.totalHours + opts.spouseHours : opts.totalHours;
  const targetHours = opts.targetTest === "substantially" ? null : parseInt(opts.targetTest, 10);

  const summaryRows: string[][] = [
    ["Total Hours Logged", `${irsHours.toFixed(1)} hours`],
    ["Annual Goal", `${opts.goalHours} hours`],
    ["Goal Status", irsHours >= opts.goalHours ? "Goal Reached" : `${Math.ceil(opts.goalHours - irsHours)} hours remaining`],
    ["Properties Tracked", `${opts.propertyBreakdown.length}`],
    ["Total Entries", `${opts.activity.length + (opts.showCombined ? opts.spouseActivity.length : 0)}`],
  ];

  if (opts.showCombined && opts.spouseName) {
    summaryRows.splice(1, 0,
      [`${opts.userName}'s Hours`, `${opts.totalHours.toFixed(1)} hours`],
      [`${opts.spouseName}'s Hours`, `${opts.spouseHours.toFixed(1)} hours`],
    );
  }

  if (targetHours) {
    summaryRows.push(["Material Participation Target", `${targetHours} hours`]);
    summaryRows.push(["Target Status", irsHours >= targetHours ? "Met" : `${Math.ceil(targetHours - irsHours)} hours remaining`]);
  } else {
    summaryRows.push(["Material Participation Target", "Substantially All"]);
  }

  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    theme: "plain",
    styles: { fontSize: 10, cellPadding: 6, textColor: CHAR },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 200 },
      1: { halign: "right" },
    },
    body: summaryRows,
    alternateRowStyles: { fillColor: [...CREAM] },
  });

  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 25;

  // ── IRS Material Participation ──────────────────────────
  checkPage(140);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...PLUM);
  doc.text("IRS Material Participation", margin, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...SLATE);
  doc.text("Per IRS regulations, taxpayers must demonstrate material participation in rental activities to deduct losses against other income.", margin, y + 10, { maxWidth: contentW });
  y += 28;

  const tests: { name: string; description: string; result: string; met: boolean }[] = [];

  if (targetHours) {
    tests.push({
      name: `${targetHours}-Hour Test`,
      description: `The taxpayer participated in the activity for more than ${targetHours} hours during the tax year.`,
      result: irsHours >= targetHours
        ? `${irsHours.toFixed(1)} hours logged — requirement met.`
        : `${irsHours.toFixed(1)} of ${targetHours} hours logged — ${Math.ceil(targetHours - irsHours)} hours remaining.`,
      met: irsHours >= targetHours,
    });
  }

  tests.push({
    name: "Record-Keeping",
    description: "Contemporaneous records of time, activity type, and property are maintained.",
    result: `${opts.activity.length + (opts.showCombined ? opts.spouseActivity.length : 0)} detailed entries logged across ${opts.propertyBreakdown.length} properties.`,
    met: true,
  });

  for (const test of tests) {
    checkPage(60);
    doc.setFillColor(test.met ? 234 : 254, test.met ? 248 : 243, test.met ? 237 : 234);
    doc.roundedRect(margin, y, contentW, 50, 4, 4, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...CHAR);
    doc.text(test.name, margin + 12, y + 16);

    const statusText = test.met ? "MET" : "IN PROGRESS";
    const statusColor = test.met ? [21, 128, 61] : [...TANGERINE];
    doc.setFontSize(8);
    doc.setTextColor(statusColor[0], statusColor[1], statusColor[2]);
    doc.text(statusText, pageW - margin - 12, y + 16, { align: "right" });

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(...SLATE);
    doc.text(test.result, margin + 12, y + 34, { maxWidth: contentW - 24 });

    y += 60;
  }

  y += 15;

  // ── Hours by Property ───────────────────────────────────
  if (opts.propertyBreakdown.length > 0) {
    checkPage(80);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(...PLUM);
    doc.text("Hours by Property", margin, y);
    y += 18;

    const propRows = opts.propertyBreakdown.map((p) => {
      const row = [p.name, `${p.hours.toFixed(1)}`];
      if (opts.showCombined && opts.spouseName) {
        row.push(`${p.mine.toFixed(1)}`);
        row.push(`${p.spouse.toFixed(1)}`);
      }
      return row;
    });

    const propHead = ["Property", "Total Hours"];
    if (opts.showCombined && opts.spouseName) {
      propHead.push(opts.userName);
      propHead.push(opts.spouseName);
    }

    const propTotalRow = [
      "Total",
      `${opts.propertyBreakdown.reduce((s, p) => s + p.hours, 0).toFixed(1)}`,
    ];
    if (opts.showCombined && opts.spouseName) {
      propTotalRow.push(`${opts.propertyBreakdown.reduce((s, p) => s + p.mine, 0).toFixed(1)}`);
      propTotalRow.push(`${opts.propertyBreakdown.reduce((s, p) => s + p.spouse, 0).toFixed(1)}`);
    }
    propRows.push(propTotalRow);

    autoTable(doc, {
      startY: y,
      margin: { left: margin, right: margin },
      head: [propHead],
      body: propRows,
      theme: "grid",
      styles: { fontSize: 9.5, cellPadding: 7, textColor: CHAR, lineColor: [...BONE], lineWidth: 0.5 },
      headStyles: { fillColor: [...PLUM], textColor: [255, 255, 255], fontStyle: "bold" },
      alternateRowStyles: { fillColor: [...CREAM] },
      columnStyles: {
        0: { cellWidth: opts.showCombined ? 200 : 340 },
        1: { halign: "right" },
        2: { halign: "right" },
        3: { halign: "right" },
      },
      didParseCell(data) {
        if (data.row.index === propRows.length - 1) {
          data.cell.styles.fontStyle = "bold";
          data.cell.styles.fillColor = [232, 228, 222];
        }
      },
    });

    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 25;
  }

  // ── Hours by Category ───────────────────────────────────
  if (opts.categoryBreakdown.length > 0) {
    checkPage(80);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(...PLUM);
    doc.text("Hours by Category", margin, y);
    y += 18;

    const catRows = opts.categoryBreakdown.map((c) => [
      c.name,
      `${c.hours.toFixed(1)}`,
      `${c.pct.toFixed(0)}%`,
    ]);

    autoTable(doc, {
      startY: y,
      margin: { left: margin, right: margin },
      head: [["Category", "Hours", "% of Total"]],
      body: catRows,
      theme: "grid",
      styles: { fontSize: 9.5, cellPadding: 7, textColor: CHAR, lineColor: [...BONE], lineWidth: 0.5 },
      headStyles: { fillColor: [...PLUM], textColor: [255, 255, 255], fontStyle: "bold" },
      alternateRowStyles: { fillColor: [...CREAM] },
      columnStyles: {
        0: { cellWidth: 300 },
        1: { halign: "right" },
        2: { halign: "right" },
      },
    });

    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 25;
  }

  // ── Detailed Activity Log ───────────────────────────────
  checkPage(60);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...PLUM);
  doc.text("Detailed Activity Log", margin, y);
  y += 18;

  const allEntries = opts.showCombined && opts.spouseName
    ? [
        ...opts.activity.map((e) => ({ ...e, loggedBy: opts.userName })),
        ...opts.spouseActivity.map((e) => ({ ...e, loggedBy: opts.spouseName! })),
      ].sort((a, b) => new Date(b.started_at).getTime() - new Date(a.started_at).getTime())
    : opts.activity.map((e) => ({ ...e, loggedBy: "" }));

  const logHead = ["Date", "Time", "Property", "Category", "Hours"];
  if (opts.showCombined && opts.spouseName) logHead.push("Logged By");

  const logRows = allEntries.map((e) => {
    const d = new Date(e.started_at);
    const row = [
      d.toLocaleDateString("en-US", { month: "2-digit", day: "2-digit", year: "numeric" }),
      d.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" }),
      e.property?.name ?? "—",
      e.title || e.category || "—",
      (e.duration_secs / 3600).toFixed(2),
    ];
    if (opts.showCombined && opts.spouseName) row.push(e.loggedBy);
    return row;
  });

  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    head: [logHead],
    body: logRows,
    theme: "grid",
    styles: { fontSize: 8, cellPadding: 5, textColor: CHAR, lineColor: [...BONE], lineWidth: 0.5, overflow: "linebreak" },
    headStyles: { fillColor: [...PLUM], textColor: [255, 255, 255], fontStyle: "bold", fontSize: 8.5 },
    alternateRowStyles: { fillColor: [...CREAM] },
    columnStyles: {
      0: { cellWidth: 70 },
      1: { cellWidth: 60 },
      4: { halign: "right", cellWidth: 45 },
    },
  });

  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 25;

  // ── Disclaimer ──────────────────────────────────────────
  checkPage(70);
  drawHr();
  doc.setFont("helvetica", "italic");
  doc.setFontSize(7.5);
  doc.setTextColor(...SLATE);
  const disclaimer = "This report is generated from self-reported data and is intended to support tax filing. It does not constitute tax advice. Consult a qualified tax professional or CPA regarding IRS material participation requirements and the deductibility of short-term rental expenses. Host Hours is a record-keeping tool and makes no representations regarding tax compliance.";
  doc.text(disclaimer, margin, y, { maxWidth: contentW });

  // ── Page footers ────────────────────────────────────────
  addPageFooter();

  // ── Save ────────────────────────────────────────────────
  const filename = `Host_Hours_Tax_Report_${opts.taxYear}${opts.propertyFilter !== "All properties" ? "_" + opts.propertyFilter.replace(/[^a-zA-Z0-9]/g, "_") : ""}.pdf`;
  doc.save(filename);
}
