import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

type ActivityEntry = {
  started_at: string;
  title: string;
  category: string;
  duration_secs: number;
  description: string | null;
  property: { name: string; address: string | null } | null;
  // Receipt/photo thumbnails as data URLs (embedded into the PDF).
  photos?: string[];
};

type PropertyBreakdown = {
  name: string;
  address: string | null;
  hours: number;
  mine: number;
  cohost: number;
};

type StaffHours = {
  name: string;
  role: string;
  hours: number;
};

type CategoryBreakdown = {
  name: string;
  hours: number;
  mine: number;
  cohost: number;
  pct: number;
};

type PdfOptions = {
  fullName: string;
  userName: string;
  cohostName: string | null;
  showCombined: boolean;
  taxYear: number;
  goalHours: number;
  targetTest: string;
  totalHours: number;
  cohostHours: number;
  propertyBreakdown: PropertyBreakdown[];
  categoryBreakdown: CategoryBreakdown[];
  activity: ActivityEntry[];
  cohostActivity: ActivityEntry[];
  propertyFilter: string;
  teamMemberCount: number;
  // Helpers/managers have no IRS material-participation target test.
  hideTargetTest?: boolean;
  // Helper & manager hours — shown separately, NOT combined into the total
  // (only an owner and spouse combine for material participation).
  staffHours?: StaffHours[];
};

const PLUM: [number, number, number] = [58, 27, 73];
const CHAR: [number, number, number] = [45, 42, 40];
const SLATE: [number, number, number] = [120, 113, 108];
const CREAM: [number, number, number] = [249, 246, 240];
const BONE: [number, number, number] = [232, 228, 222];

export function generateTaxPdf(opts: PdfOptions) {
  const doc = new jsPDF({ orientation: "portrait", unit: "pt", format: "letter" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 50;
  const contentW = pageW - margin * 2;
  let y = margin;

  function addPageFooter() {
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(...SLATE);
      doc.text(
        `Generated by Host Hours · ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`,
        margin,
        pageH - 30,
      );
      doc.text(`Page ${i} of ${pageCount}`, pageW - margin, pageH - 30, { align: "right" });
    }
  }

  function checkPage(needed: number) {
    if (y + needed > pageH - 60) {
      doc.addPage();
      y = margin;
    }
  }

  function drawHr() {
    doc.setDrawColor(...BONE);
    doc.setLineWidth(0.5);
    doc.line(margin, y, pageW - margin, y);
    y += 12;
  }

  // ── Header ──────────────────────────────────────────────
  doc.setFillColor(...PLUM);
  doc.rect(0, 0, pageW, 90, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  doc.text("Hours Tracking Report", margin, 40);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(200, 180, 210);
  doc.text("Short-Term Rental Activity", margin, 58);

  doc.setFontSize(18);
  doc.setTextColor(255, 255, 255);
  doc.text(`${opts.taxYear}`, pageW - margin, 40, { align: "right" });

  doc.setFontSize(11);
  doc.setTextColor(200, 180, 210);
  const displayName = opts.showCombined && opts.cohostName
    ? `${opts.fullName} & ${opts.cohostName}`
    : opts.fullName;
  doc.text(displayName, pageW - margin, 58, { align: "right" });

  if (opts.propertyFilter !== "All properties") {
    doc.setFontSize(9);
    doc.setTextColor(200, 180, 210);
    doc.text(`Property: ${opts.propertyFilter}`, pageW - margin, 74, { align: "right" });
  }

  y = 115;

  // ── Summary Section ─────────────────────────────────────
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...PLUM);
  doc.text("Summary", margin, y);
  y += 20;

  // Combined household total (owner + spouse) when there's a spouse.
  const irsHours = opts.showCombined ? opts.totalHours + opts.cohostHours : opts.totalHours;

  const summaryRows: string[][] = [
    ["Total Hours Logged", `${irsHours.toFixed(1)} hours`],
  ];

  // Per-person breakdown of the combined total.
  if (opts.showCombined && opts.cohostName) {
    summaryRows.push(
      [`${opts.userName}'s Hours`, `${opts.totalHours.toFixed(1)} hours`],
      [`${opts.cohostName}'s Hours`, `${opts.cohostHours.toFixed(1)} hours`],
    );
  }

  summaryRows.push(["Properties Tracked", `${opts.propertyBreakdown.length}`]);

  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    theme: "plain",
    styles: { fontSize: 10, cellPadding: 6, textColor: CHAR },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 220 },
      1: { halign: "right" },
    },
    body: summaryRows,
    alternateRowStyles: { fillColor: [...CREAM] },
  });

  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 25;

  // ── Hours by Property ───────────────────────────────────
  if (opts.propertyBreakdown.length > 0) {
    checkPage(80);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(...PLUM);
    doc.text("Hours by Property", margin, y);
    y += 18;

    const propRows = opts.propertyBreakdown.map((p) => {
      const row = [p.address || p.name, `${p.hours.toFixed(1)}`];
      if (opts.showCombined && opts.cohostName) {
        row.push(`${p.mine.toFixed(1)}`);
        row.push(`${p.cohost.toFixed(1)}`);
      }
      return row;
    });

    const propHead = ["Property", "Total Hours"];
    if (opts.showCombined && opts.cohostName) {
      propHead.push(opts.userName);
      propHead.push(opts.cohostName);
    }

    const propTotalRow = [
      "Total",
      `${opts.propertyBreakdown.reduce((s, p) => s + p.hours, 0).toFixed(1)}`,
    ];
    if (opts.showCombined && opts.cohostName) {
      propTotalRow.push(`${opts.propertyBreakdown.reduce((s, p) => s + p.mine, 0).toFixed(1)}`);
      propTotalRow.push(`${opts.propertyBreakdown.reduce((s, p) => s + p.cohost, 0).toFixed(1)}`);
    }
    propRows.push(propTotalRow);

    autoTable(doc, {
      startY: y,
      margin: { left: margin, right: margin },
      head: [propHead],
      body: propRows,
      theme: "grid",
      styles: { fontSize: 9.5, cellPadding: 7, textColor: CHAR, lineColor: [...BONE], lineWidth: 0.5 },
      headStyles: { fillColor: [...PLUM], textColor: [255, 255, 255], fontStyle: "bold" },
      alternateRowStyles: { fillColor: [...CREAM] },
      columnStyles: {
        0: { cellWidth: opts.showCombined ? 200 : 340 },
        1: { halign: "right" },
        2: { halign: "right" },
        3: { halign: "right" },
      },
      didParseCell(data) {
        if (data.row.index === propRows.length - 1) {
          data.cell.styles.fontStyle = "bold";
          data.cell.styles.fillColor = [232, 228, 222];
        }
      },
    });

    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 25;
  }

  // ── Helper & Manager Hours (reference only — not combined) ──
  if (opts.staffHours && opts.staffHours.length > 0) {
    checkPage(90);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(...PLUM);
    doc.text("Helper & Manager Hours", margin, y);
    y += 14;
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8.5);
    doc.setTextColor(...SLATE);
    doc.text(
      "Shown for reference. These hours are NOT combined into the material-participation total above.",
      margin,
      y,
    );
    y += 12;

    autoTable(doc, {
      startY: y,
      margin: { left: margin, right: margin },
      head: [["Name", "Role", "Hours"]],
      body: opts.staffHours.map((s) => [s.name, s.role, s.hours.toFixed(1)]),
      theme: "grid",
      styles: { fontSize: 9.5, cellPadding: 7, textColor: CHAR, lineColor: [...BONE], lineWidth: 0.5 },
      headStyles: { fillColor: [...PLUM], textColor: [255, 255, 255], fontStyle: "bold" },
      alternateRowStyles: { fillColor: [...CREAM] },
      columnStyles: { 2: { halign: "right", cellWidth: 80 } },
    });

    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 25;
  }

  // ── Detailed Activity Log (per person, kept separate) ───
  const logHead = [["Date", "Started", "Property", "Task, Details & Notes", "Photos", "Hours"]];
  const PHOTO_COL = 4;
  const THUMB = 180;
  const PHOTO_GAP = 6;
  const PHOTO_PAD = 5;
  // Most photos that fit stacked in one page-tall row. Extras spill onto
  // "continuation" rows so a row never exceeds a page (which would clip).
  const MAX_PHOTOS_PER_CELL = 3;
  const logColumnStyles = {
    0: { cellWidth: 58 },
    1: { cellWidth: 50 },
    4: { cellWidth: THUMB + 2 * PHOTO_PAD },
    5: { halign: "right" as const, cellWidth: 42 },
  };

  function drawActivityLog(title: string, entries: ActivityEntry[]) {
    checkPage(60);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(...PLUM);
    doc.text(title, margin, y);
    y += 18;

    const sorted = [...entries].sort(
      (a, b) => new Date(b.started_at).getTime() - new Date(a.started_at).getTime(),
    );

    // Build one row per entry, plus continuation rows for photo overflow so a
    // single row's photos never exceed a page (they flow onto the next page).
    const rowPhotos: string[][] = [];
    const body: string[][] = [];
    for (const e of sorted) {
      const d = new Date(e.started_at);
      const task = e.title || e.category || "—";
      const taskCell = e.description?.trim() ? `${task}\n${e.description.trim()}` : task;
      const textCells = [
        d.toLocaleDateString("en-US", { month: "2-digit", day: "2-digit", year: "numeric" }),
        d.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" }),
        e.property?.address || e.property?.name || "—",
        taskCell,
        "",
        (e.duration_secs / 3600).toFixed(2),
      ];
      const photos = e.photos ?? [];
      if (photos.length <= MAX_PHOTOS_PER_CELL) {
        body.push(textCells);
        rowPhotos.push(photos);
      } else {
        for (let i = 0; i < photos.length; i += MAX_PHOTOS_PER_CELL) {
          // First chunk carries the entry's text; the rest are photo-only rows.
          body.push(i === 0 ? textCells : ["", "", "", "", "", ""]);
          rowPhotos.push(photos.slice(i, i + MAX_PHOTOS_PER_CELL));
        }
      }
    }

    autoTable(doc, {
      startY: y,
      margin: { left: margin, right: margin, bottom: 50 },
      head: logHead,
      body,
      theme: "grid",
      styles: { fontSize: 8, cellPadding: 5, textColor: CHAR, lineColor: [...BONE], lineWidth: 0.5, overflow: "linebreak", valign: "top" },
      headStyles: { fillColor: [...PLUM], textColor: [255, 255, 255], fontStyle: "bold", fontSize: 8.5 },
      alternateRowStyles: { fillColor: [...CREAM] },
      columnStyles: logColumnStyles,
      didParseCell(data) {
        // Grow the row to fit this row's stacked photos.
        if (data.section === "body" && data.column.index === PHOTO_COL) {
          const n = rowPhotos[data.row.index]?.length ?? 0;
          if (n > 0) {
            data.cell.styles.minCellHeight =
              n * (THUMB + PHOTO_GAP) - PHOTO_GAP + 2 * PHOTO_PAD;
          }
        }
      },
      didDrawCell(data) {
        if (data.section === "body" && data.column.index === PHOTO_COL) {
          const photos = rowPhotos[data.row.index] ?? [];
          photos.forEach((p, i) => {
            const ix = data.cell.x + (data.cell.width - THUMB) / 2;
            const iy = data.cell.y + PHOTO_PAD + i * (THUMB + PHOTO_GAP);
            try {
              doc.addImage(p, p.startsWith("data:image/png") ? "PNG" : "JPEG", ix, iy, THUMB, THUMB);
            } catch {
              // skip unsupported/corrupt images
            }
          });
        }
      },
    });

    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 25;
  }

  // Primary person's log, then the spouse's log in its own table.
  const combinedWithSpouse = opts.showCombined && !!opts.cohostName;
  drawActivityLog(
    combinedWithSpouse ? `Detailed Activity Log — ${opts.userName}` : "Detailed Activity Log",
    opts.activity,
  );
  if (combinedWithSpouse) {
    drawActivityLog(`Detailed Activity Log — ${opts.cohostName}`, opts.cohostActivity);
  }

  // ── Disclaimer ──────────────────────────────────────────
  checkPage(70);
  drawHr();
  doc.setFont("helvetica", "italic");
  doc.setFontSize(7.5);
  doc.setTextColor(...SLATE);
  const disclaimer = "This report is generated from self-reported data and is intended to support tax filing. It does not constitute tax advice. Consult a qualified tax professional or CPA regarding IRS material participation requirements and the deductibility of short-term rental expenses. Host Hours is a record-keeping tool and makes no representations regarding tax compliance.";
  doc.text(disclaimer, margin, y, { maxWidth: contentW });

  // ── Page footers ────────────────────────────────────────
  addPageFooter();

  // ── Save ────────────────────────────────────────────────
  const filename = `Hours_Tracking_Report_${opts.taxYear}${opts.propertyFilter !== "All properties" ? "_" + opts.propertyFilter.replace(/[^a-zA-Z0-9]/g, "_") : ""}.pdf`;
  doc.save(filename);
}
