import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

type ActivityEntry = {
  started_at: string;
  title: string;
  category: string;
  duration_secs: number;
  description: string | null;
  property: { name: string; address: string | null } | null;
};

type PropertyBreakdown = {
  name: string;
  hours: number;
  mine: number;
  cohost: number;
};

type CategoryBreakdown = {
  name: string;
  hours: number;
  mine: number;
  cohost: number;
  pct: number;
};

type PdfOptions = {
  fullName: string;
  userName: string;
  cohostName: string | null;
  showCombined: boolean;
  taxYear: number;
  goalHours: number;
  targetTest: string;
  totalHours: number;
  cohostHours: number;
  propertyBreakdown: PropertyBreakdown[];
  categoryBreakdown: CategoryBreakdown[];
  activity: ActivityEntry[];
  cohostActivity: ActivityEntry[];
  propertyFilter: string;
  teamMemberCount: number;
};

const PLUM = [58, 27, 73] as const;
const CHAR = [45, 42, 40] as const;
const SLATE = [120, 113, 108] as const;
const CREAM = [249, 246, 240] as const;
const BONE = [232, 228, 222] as const;

export function generateTaxPdf(opts: PdfOptions) {
  const doc = new jsPDF({ orientation: "portrait", unit: "pt", format: "letter" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 50;
  const contentW = pageW - margin * 2;
  let y = margin;

  function addPageFooter() {
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(...SLATE);
      doc.text(
        `Generated by Host Hours · ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`,
        margin,
        pageH - 30,
      );
      doc.text(`Page ${i} of ${pageCount}`, pageW - margin, pageH - 30, { align: "right" });
    }
  }

  function checkPage(needed: number) {
    if (y + needed > pageH - 60) {
      doc.addPage();
      y = margin;
    }
  }

  function drawHr() {
    doc.setDrawColor(...BONE);
    doc.setLineWidth(0.5);
    doc.line(margin, y, pageW - margin, y);
    y += 12;
  }

  // ── Header ──────────────────────────────────────────────
  doc.setFillColor(...PLUM);
  doc.rect(0, 0, pageW, 90, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  doc.text("Hours Tracking Report", margin, 40);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(200, 180, 210);
  doc.text("Short-Term Rental Activity", margin, 58);

  doc.setFontSize(18);
  doc.setTextColor(255, 255, 255);
  doc.text(`${opts.taxYear}`, pageW - margin, 40, { align: "right" });

  doc.setFontSize(11);
  doc.setTextColor(200, 180, 210);
  const displayName = opts.showCombined && opts.cohostName
    ? `${opts.fullName} & ${opts.cohostName}`
    : opts.fullName;
  doc.text(displayName, pageW - margin, 58, { align: "right" });

  if (opts.propertyFilter !== "All properties") {
    doc.setFontSize(9);
    doc.setTextColor(200, 180, 210);
    doc.text(`Property: ${opts.propertyFilter}`, pageW - margin, 74, { align: "right" });
  }

  y = 115;

  // ── Summary Section ─────────────────────────────────────
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...PLUM);
  doc.text("Summary", margin, y);
  y += 20;

  const irsHours = opts.showCombined ? opts.totalHours + opts.cohostHours : opts.totalHours;
  const targetHours = opts.targetTest === "substantially" ? null : parseInt(opts.targetTest, 10);
  const totalEntries = opts.activity.length + (opts.showCombined ? opts.cohostActivity.length : 0);

  const summaryRows: string[][] = [
    ["Total Hours Logged", `${irsHours.toFixed(1)} hours`],
  ];

  if (opts.showCombined && opts.cohostName) {
    summaryRows.push(
      [`${opts.userName}'s Hours`, `${opts.totalHours.toFixed(1)} hours`],
      [`${opts.cohostName}'s Hours`, `${opts.cohostHours.toFixed(1)} hours`],
    );
  }

  summaryRows.push(
    ["Properties Tracked", `${opts.propertyBreakdown.length}`],
    ["Total Time Entries", `${totalEntries}`],
  );

  if (targetHours === 500) {
    summaryRows.push(
      ["Material Participation Test", "500-Hour Test"],
      ["Target", "500 hours"],
      ["Status", irsHours >= 500 ? "Met" : `${Math.ceil(500 - irsHours)} hours remaining`],
    );
  } else if (targetHours === 100) {
    summaryRows.push(
      ["Material Participation Test", "100-Hour / Significant Participation Test"],
      ["Target", "100 hours"],
      ["Status", irsHours >= 100 ? "Met" : `${Math.ceil(100 - irsHours)} hours remaining`],
    );
    if (opts.teamMemberCount > 0) {
      summaryRows.push(
        ["Team Members", `${opts.teamMemberCount}`],
        ["Note", "Participation must not be less than any other individual's participation"],
      );
    }
  }
  // For "substantially" — no goal/status rows needed

  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    theme: "plain",
    styles: { fontSize: 10, cellPadding: 6, textColor: CHAR },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 220 },
      1: { halign: "right" },
    },
    body: summaryRows,
    alternateRowStyles: { fillColor: [...CREAM] },
  });

  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 25;

  // ── Hours by Property ───────────────────────────────────
  if (opts.propertyBreakdown.length > 0) {
    checkPage(80);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(...PLUM);
    doc.text("Hours by Property", margin, y);
    y += 18;

    const propRows = opts.propertyBreakdown.map((p) => {
      const row = [p.name, `${p.hours.toFixed(1)}`];
      if (opts.showCombined && opts.cohostName) {
        row.push(`${p.mine.toFixed(1)}`);
        row.push(`${p.cohost.toFixed(1)}`);
      }
      return row;
    });

    const propHead = ["Property", "Total Hours"];
    if (opts.showCombined && opts.cohostName) {
      propHead.push(opts.userName);
      propHead.push(opts.cohostName);
    }

    const propTotalRow = [
      "Total",
      `${opts.propertyBreakdown.reduce((s, p) => s + p.hours, 0).toFixed(1)}`,
    ];
    if (opts.showCombined && opts.cohostName) {
      propTotalRow.push(`${opts.propertyBreakdown.reduce((s, p) => s + p.mine, 0).toFixed(1)}`);
      propTotalRow.push(`${opts.propertyBreakdown.reduce((s, p) => s + p.cohost, 0).toFixed(1)}`);
    }
    propRows.push(propTotalRow);

    autoTable(doc, {
      startY: y,
      margin: { left: margin, right: margin },
      head: [propHead],
      body: propRows,
      theme: "grid",
      styles: { fontSize: 9.5, cellPadding: 7, textColor: CHAR, lineColor: [...BONE], lineWidth: 0.5 },
      headStyles: { fillColor: [...PLUM], textColor: [255, 255, 255], fontStyle: "bold" },
      alternateRowStyles: { fillColor: [...CREAM] },
      columnStyles: {
        0: { cellWidth: opts.showCombined ? 200 : 340 },
        1: { halign: "right" },
        2: { halign: "right" },
        3: { halign: "right" },
      },
      didParseCell(data) {
        if (data.row.index === propRows.length - 1) {
          data.cell.styles.fontStyle = "bold";
          data.cell.styles.fillColor = [232, 228, 222];
        }
      },
    });

    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 25;
  }

  // ── Detailed Activity Log ───────────────────────────────
  checkPage(60);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...PLUM);
  doc.text("Detailed Activity Log", margin, y);
  y += 18;

  const allEntries = opts.showCombined && opts.cohostName
    ? [
        ...opts.activity.map((e) => ({ ...e, loggedBy: opts.userName })),
        ...opts.cohostActivity.map((e) => ({ ...e, loggedBy: opts.cohostName! })),
      ].sort((a, b) => new Date(b.started_at).getTime() - new Date(a.started_at).getTime())
    : opts.activity.map((e) => ({ ...e, loggedBy: "" }));

  const logHead = ["Date", "Time", "Property", "Task & Details", "Hours"];
  if (opts.showCombined && opts.cohostName) logHead.push("Logged By");

  const logRows = allEntries.map((e) => {
    const d = new Date(e.started_at);
    const row = [
      d.toLocaleDateString("en-US", { month: "2-digit", day: "2-digit", year: "numeric" }),
      d.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" }),
      e.property?.name ?? "—",
      e.title || e.category || "—",
      (e.duration_secs / 3600).toFixed(2),
    ];
    if (opts.showCombined && opts.cohostName) row.push(e.loggedBy);
    return row;
  });

  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    head: [logHead],
    body: logRows,
    theme: "grid",
    styles: { fontSize: 8, cellPadding: 5, textColor: CHAR, lineColor: [...BONE], lineWidth: 0.5, overflow: "linebreak" },
    headStyles: { fillColor: [...PLUM], textColor: [255, 255, 255], fontStyle: "bold", fontSize: 8.5 },
    alternateRowStyles: { fillColor: [...CREAM] },
    columnStyles: {
      0: { cellWidth: 70 },
      1: { cellWidth: 60 },
      4: { halign: "right", cellWidth: 45 },
    },
  });

  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 25;

  // ── Disclaimer ──────────────────────────────────────────
  checkPage(70);
  drawHr();
  doc.setFont("helvetica", "italic");
  doc.setFontSize(7.5);
  doc.setTextColor(...SLATE);
  const disclaimer = "This report is generated from self-reported data and is intended to support tax filing. It does not constitute tax advice. Consult a qualified tax professional or CPA regarding IRS material participation requirements and the deductibility of short-term rental expenses. Host Hours is a record-keeping tool and makes no representations regarding tax compliance.";
  doc.text(disclaimer, margin, y, { maxWidth: contentW });

  // ── Page footers ────────────────────────────────────────
  addPageFooter();

  // ── Save ────────────────────────────────────────────────
  const filename = `Hours_Tracking_Report_${opts.taxYear}${opts.propertyFilter !== "All properties" ? "_" + opts.propertyFilter.replace(/[^a-zA-Z0-9]/g, "_") : ""}.pdf`;
  doc.save(filename);
}
